server:
  port: 8889
#Spring整合Mybatis
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/lottery?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: fsfs

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest



mybatis:
  #定义别名包
  type-aliases-package: com.example.lottery.model
  #配置映射文件路径
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    #打映sql语句
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启驼峰映射
    map-underscore-to-camel-case: true

